config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('news_app.urls')),
    path('account/', include('accounts.urls')),

)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

news_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=News.Status.Published)


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class News(models.Model):
    class Status(models.TextChoices):
        Draft = 'DF', 'Draft'
        Published = 'PB', 'Published'

    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='news',
                               null=True,
                               blank=True)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    body = models.TextField()
    image = models.ImageField(upload_to='news/images')
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    published_time = models.DateTimeField(default=timezone.now)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.Draft
                              )

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-published_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news_detail_page', args=[self.slug])


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.email


class Comment(models.Model):
    news = models.ForeignKey(News,
                             on_delete=models.CASCADE,
                             related_name='comments')
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='comments', )
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_time']

    def __str__(self):
        return f'Comment - \'{self.body[:20]}\' by {self.user}'

templates/crud/news_create.html
{% extends 'news/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% blocktrans %} Yangilik yaratish {% endblocktrans %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            {% include 'pages/profile_sidebar.html' %}
        </div>
        <div class="col-md-9">
            <h3>{% blocktrans %} Yangilik yaratish {% endblocktrans %}</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">{% blocktrans %} Saqlash {% endblocktrans %}</button>
            </form>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function slugify(text) {
        return text.toString().toLowerCase()
            .replace(/\s+/g, '-')           // Replace spaces with -
            .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
            .replace(/\-\-+/g, '-')         // Replace multiple - with single -
            .replace(/^-+/, '')             // Trim - from start of text
            .replace(/-+$/, '');            // Trim - from end of text
    }

    $(document).ready(function() {
        $('#id_title').on('input', function() {
            const title = $(this).val();
            const slug = slugify(title);
            $('#id_slug').val(slug);
        });
    });
</script>
{% endblock content %}

templates/crud/news_delete.html
{% extends 'news/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
{% blocktrans %} Yangilikni o'chirish {% endblocktrans %}
{% endblock %}
{% block content %}
    
    <h2 class="text-center">{% blocktrans %} Joriy yangilikni o'chirish {% endblocktrans %}</h2>
    <form method="post">{% csrf_token %}
        <p>{{ news.title | truncatewords:5 }}... {% blocktrans %} sarlavhali yangilikni o'chirishni istaysizmi? {% endblocktrans %}</p>
        <button type="submit" class="btn btn-danger ml-2">{% blocktrans %} Tasdiqlayman {% endblocktrans %}</button>
    </form>
    
{% endblock content %}

templates/crud/news_edit.html
{% extends 'news/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
{% blocktrans %} Yangilikni tahrirlash {% endblocktrans %}
{% endblock %}
{% block content %}

    <h2 class="text-center">{% blocktrans %} Joriy yangilikni tahrirlash {% endblocktrans %}</h2>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-info ml-2">{% blocktrans %} Saqlash {% endblocktrans %}</button>
    </form>
    
{% endblock content %}